import {
    LayoutDashboard,
    Package,
    User,
    Warehouse,
    Shield,
    Building,
    ShoppingCart,
    Briefcase,
    Store,
    Truck,
    BarChart,
    Receipt,
    Check,
    FileText,
    Box,
    BarChart2,
    Coins,
} from "lucide-react";

import { NavLinkProps } from "@/types/nav-link";

import { RoleList } from "@/constants/config";

export const LINKS: (Omit<NavLinkProps, "variant"> & { children?: Omit<NavLinkProps, "variant">[] })[] = [
    {
        key: "dashboard",
        title: "Dashboard",
        icon: LayoutDashboard,
        href: "/admin/dashboard",
        allowedRoles: ["*"],
    },
    {
        key: "approval",
        title: "Approval",
        icon: Check,
        href: "/admin/approval",
        allowedRoles: ["*", RoleList.MANAGER, RoleList.FINANCE, RoleList.JOB_POSTER_ADMIN, RoleList.ADMIN],
    },
    {
        key: "order",
        title: "Sales Order",
        icon: ShoppingCart,
        href: "/admin/order",
        allowedRoles: ["*", RoleList.MANAGER, RoleList.PRODUCT_MANAGER],
    },
    {
        key: "collect-payment",
        title: "Collect Payment",
        icon: Coins,
        href: "/admin/collect-payment",
        allowedRoles: ["*", RoleList.MANAGER, RoleList.FINANCE],
    },
    {
        key: "audit-log",
        title: "Audit Log",
        icon: FileText,
        href: "/admin/audit-log",
        allowedRoles: ["*", RoleList.MANAGER, RoleList.ADMIN],
    },
    {
        key: "invoice",
        title: "E-Invoice",
        icon: Receipt,
        href: "#",
        allowedRoles: ["*", RoleList.MANAGER, RoleList.FINANCE],
        children: [
            {
                key: "statement",
                title: "Statement",
                icon: FileText,
                href: "/admin/statement",
                allowedRoles: ["*", RoleList.MANAGER, RoleList.FINANCE],
            },
            {
                key: "invoice",
                title: "Invoice",
                icon: Receipt,
                href: "/admin/invoice",
                allowedRoles: ["*", RoleList.MANAGER, RoleList.FINANCE],
            },
            {
                key: "credit-note",
                title: "Credit Note",
                icon: FileText,
                href: "/admin/credit-note",
                allowedRoles: ["*", RoleList.MANAGER, RoleList.FINANCE],
            },
            {
                key: "debit-note",
                title: "Debit Note",
                icon: FileText,
                href: "/admin/debit-note",
                allowedRoles: ["*", RoleList.MANAGER, RoleList.FINANCE],
            },
        ],
    },
    {
        key: "settlement",
        title: "Settlement",
        icon: FileText,
        href: "/admin/settlement",
        allowedRoles: ["*", RoleList.MANAGER, RoleList.FINANCE],
    },
    {
        key: "promotion",
        title: "Promotion",
        icon: Package,
        href: "/admin/promotion",
        allowedRoles: ["*", RoleList.MANAGER, RoleList.PRODUCT_MANAGER],
    },
    {
        key: "product",
        title: "Product",
        icon: Package,
        href: "/admin/product",
        allowedRoles: ["*", RoleList.MANAGER, RoleList.PRODUCT_MANAGER, RoleList.BRAND_OWNER],
    },
    {
        key: "inventory",
        title: "Inventory",
        icon: Box,
        href: "#",
        allowedRoles: ["*", RoleList.MANAGER, RoleList.PRODUCT_MANAGER],
        children: [
            {
                key: "warehouse",
                title: "Warehouse",
                icon: Warehouse,
                href: "/admin/warehouse",
                allowedRoles: ["*", RoleList.MANAGER, RoleList.PRODUCT_MANAGER],
            },
            {
                key: "supplier-order",
                title: "Supplier Order",
                icon: Truck,
                href: "/admin/supplier-order",
                allowedRoles: ["*", RoleList.MANAGER, RoleList.PRODUCT_MANAGER],
            },
            {
                key: "goods-return",
                title: "Goods Return",
                icon: Truck,
                href: "/admin/goods-return",
                allowedRoles: ["*", RoleList.MANAGER, RoleList.PRODUCT_MANAGER],
            },
        ],
    },
    {
        key: "catalog-stock-take",
        title: "Catalog & Stock Take",
        icon: Store,
        href: "/admin/stock-catalog",
        allowedRoles: ["*", RoleList.MANAGER, RoleList.PRODUCT_MANAGER, RoleList.BRAND_OWNER],
    },
    {
        key: "outlet",
        title: "Outlet",
        icon: Building,
        href: "/admin/outlet",
        allowedRoles: ["*", RoleList.MANAGER, RoleList.JOB_POSTER_ADMIN],
    },
    {
        key: "job",
        title: "Job",
        icon: Briefcase,
        href: "/admin/job",
        allowedRoles: ["*", RoleList.MANAGER, RoleList.JOB_POSTER_ADMIN],
    },
    {
        key: "field-operation-staff",
        title: "Field Operation Staff",
        icon: Store,
        href: "/admin/field-operation-staff",
        allowedRoles: ["*", RoleList.MANAGER, RoleList.JOB_POSTER_ADMIN],
    },
    {
        key: "report",
        title: "Report",
        icon: BarChart,
        href: "#",
        allowedRoles: ["*", RoleList.MANAGER, RoleList.FINANCE],
        children: [
            {
                key: "supplier-po",
                title: "Supplier PO",
                icon: Truck,
                href: "/admin/report/supplier-po",
                allowedRoles: ["*", RoleList.MANAGER, RoleList.FINANCE],
            },
            {
                key: "outlet-sales",
                title: "Outlet Sales",
                icon: Store,
                href: "/admin/report/outlet-sales",
                allowedRoles: ["*", RoleList.MANAGER, RoleList.FINANCE],
            },
            {
                key: "salesman-performance",
                title: "Salesman Performance",
                icon: User,
                href: "/admin/report/salesman-performance",
                allowedRoles: ["*", RoleList.MANAGER, RoleList.FINANCE],
            },
            {
                key: "sku-performance",
                title: "SKU Performance",
                icon: Package,
                href: "/admin/report/sku-performance",
                allowedRoles: ["*", RoleList.MANAGER, RoleList.FINANCE],
            },
            {
                key: "inventory-skus-by-warehouse",
                title: "Inventory SKUs by Warehouse",
                icon: Box,
                href: "/admin/report/inventory-skus-by-warehouse",
                allowedRoles: ["*", RoleList.MANAGER, RoleList.FINANCE],
            },
        ],
    },
    {
        key: "role",
        title: "Roles",
        icon: Shield,
        href: "/admin/role",
        allowedRoles: ["*", RoleList.MANAGER, RoleList.ADMIN],
    },
    {
        key: "user",
        title: "User",
        icon: User,
        href: "/admin/user",
        allowedRoles: ["*", RoleList.MANAGER, RoleList.ADMIN],
    },
    {
        key: "compare",
        title: "Compare",
        icon: BarChart2,
        href: "#",
        allowedRoles: ["*", RoleList.MANAGER, RoleList.FINANCE],
        children: [
            {
                key: "sku",
                title: "SKU Performance",
                icon: Package,
                href: "/admin/compare/sku-performance",
                allowedRoles: ["*", RoleList.MANAGER, RoleList.FINANCE],
            },
            {
                key: "salesman",
                title: "Salesman Performance",
                icon: User,
                href: "/admin/compare/salesman-performance",
                allowedRoles: ["*", RoleList.MANAGER, RoleList.FINANCE],
            },
            {
                key: "outlet",
                title: "Outlet Performance",
                icon: Store,
                href: "/admin/compare/outlet-performance",
                allowedRoles: ["*", RoleList.MANAGER, RoleList.FINANCE],
            },
        ],
    },
];
