import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

import { routing } from "@/i18n/routing";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: {
        template: "%s | MetaMynd",
        default: "MetaMynd",
    },
    description: "Generated by create next app"
};

export default async function LocaleLayout(props: { children: React.ReactNode; params: Promise<{ locale: string }> }) {
    const params = await props.params;

    const { locale } = params;

    const { children } = props;

    // unstable_setRequestLocale(locale);
    const messages = await getMessages();

    return <NextIntlClientProvider messages={messages}>{children}</NextIntlClientProvider>;
}

export function generateStaticParams() {
    return routing.locales.map((locale) => ({ locale }));
}
